"""Shared configuration for Sara Modal services."""

MODEL_NAME = "Alfaxad/Sara-1.5-4B-it"
MODEL_REVISION = "main"

MINUTES = 60
GPU_WARM_WINDOW = 15 * MINUTES
REQUEST_TIMEOUT = 10 * MINUTES

SARA_GPU = "A100"
SARA_CONCURRENT_INPUTS = 8

AGENT_CPU = 1.0
AGENT_MEMORY = 2048
AGENT_CONCURRENT_INPUTS = 50

FHIR_CPU = 2.0
FHIR_MEMORY = 4096
FHIR_CONCURRENT_INPUTS = 100
